leave_app/urls.py
from django.urls import path
from leave_app.views import *


app_name = 'leave_app'

urlpatterns = [
    path('otpusk/', OtpuskListView.as_view(), name='otpusk_list'),
    path('otgul/', OtgulListView.as_view(), name='otgul_list'),
    path('create/', OtpuskCreateView.as_view(), name='form_create'),
    path('create2/', OtgulCreateView.as_view(), name='form_create_2'),
    path('otkaz/<int:app_id>/', otkaz_view),
]

personal_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leave-app/', include('leave_app.urls')),
]

leave_app/models.py
from django.db import models


#Отказ
class Otkaz(models.Model):
    note = models.TextField(blank=False, verbose_name='Причина отказа')
    name = models.CharField(max_length=96, verbose_name='ФИО')

    class Meta:
        verbose_name = 'Отказ'
        verbose_name_plural = 'Отказы'

    def __str__(self):
        return f'Отказ № {self.id}'

#Заявка на отпуск и отгул
class Base(models.Model):
    note = models.TextField(blank=False, verbose_name='Примечание')
    name = models.CharField(max_length=96, verbose_name='ФИО')
    # odobreno = models.BooleanField(default=False, blank=False, verbose_name='Заявка одобрена')
    otkaz = models.ForeignKey(Otkaz, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Отказ')
    #1 отказ может идти к нескольким заявкам
    prosmotreno = models.BooleanField(default=False, blank=False, verbose_name='Заявка просмотрена')
    created_date=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    edit_date=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')

    class Meta:
        abstract = True

#Заявка на отпуск наслудется от Base
class Otpusk(Base):
    start_date = models.DateField(blank=False, verbose_name='Начало отпуска')
    end_date = models.DateField(blank=False, verbose_name='Конец отпуска')

    class Meta:
        verbose_name = 'Заявка на отпуск'
        verbose_name_plural = 'Заявки на отпуск'
        ordering = ['-created_date', '-edit_date']

    def __str__(self):
        return f'Заявка на отпуск № {self.id}'

#Заявка на отгул наслудется от Base
class Otgul(Base):
    date = models.DateField(blank=False, verbose_name='Дата')

    class Meta:
        verbose_name = 'Заявка на отгул'
        verbose_name_plural = 'Заявки на отгул'
        ordering = ['-created_date', '-edit_date']

    def __str__(self):
        return f'Заявка на отгул № {self.id}'

leave_app/forms.py
from django import forms
from leave_app.models import *


#форма заявки на отпуск
class OtpuskForm(forms.ModelForm):
    class Meta:
        model = Otpusk
        fields = ['name', 'note']

#форма заявки на отгул
class OtgulForm(forms.ModelForm):
    class Meta:
        model = Otgul
        fields = ['name', 'note']

#форма отказа
class OtkazForm(forms.Form):
    # prosmotreno = forms.BooleanField()
    odobreno = forms.BooleanField(required=False)
    note = forms.CharField(widget=forms.Textarea, required=False)
    name=forms.CharField(required=False)
 

#фильтрация
class FilterForm(forms.Form):
    CHOICES = (
        ('1', 'Все заявки'),
        ('2', 'Обработанные'),
        ('3', 'Необработанные'),
    )
    filter = forms.ChoiceField(choices=CHOICES)

leave_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from leave_app.models import *
from leave_app.forms import *
from django.views.generic.edit import CreateView
# from django.shortcuts import redirect


class OtpuskListView(ListView):
    model = Otpusk
    template_name = 'leave_app/otpusk_list.html'
    context_object_name = 'otpusk_list'

    def get(self, *args, **kwargs):
        form = FilterForm(self.request.GET)
        if form.is_valid():
            filter = int(form.cleaned_data['filter'])

            if filter == 1:
                otpusk_list = self.model.objects.all()
            elif filter == 2:
                otpusk_list = self.model.objects.filter(prosmotreno=True)
            else: 
                otpusk_list = self.model.objects.filter(prosmotreno=False)

        else:
            otpusk_list = self.model.objects.all()
        return render (self.request, self.template_name, {self.context_object_name: otpusk_list, 'filter_form': form})


class OtgulListView(OtpuskListView):
    model = Otgul
    template_name = 'leave_app/otgul_list.html'
    context_object_name = 'otgul_list'


class OtpuskCreateView(CreateView):
    model = Otpusk
    fields = ['name', 'start_date', 'end_date', 'note']
    template_name = 'leave_app/form_create.html'
    success_url = '/leave-app/otpusk/'

class OtgulCreateView(CreateView):
    model = Otgul
    fields = ['name', 'date', 'note']
    template_name = 'leave_app/form_create_2.html'
    success_url = '/leave-app/otgul/'



def otkaz_view(request, app_id):
    if request.method == "POST":
        if 'is_otpusk' in request.GET and request.GET.get('is_otpusk') == 'True':
            application = Otpusk.objects.get(id=app_id)
            object_type = 'otpusk'
        else:
            application = Otgul.objects.get(id=app_id)
            object_type = 'otgul'

        form = OtkazForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            application.prosmotreno = True

            if cd['odobreno']:
                application.save()
            else:
                otkaz = Otkaz(note=cd['note'], name=cd['name'])
                otkaz.save()

                application.otkaz = otkaz
                application.save()
            return redirect(f'/leave-app/{object_type}/')
    else:
        form = OtkazForm()

    return render(request, 'leave_app/otkaz.html', {'form': form})

leave_app/templates/leave_app/form_create.html
{%extends 'root.html'%}

{%block content%}
<div>
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Отправить</button>
    </form>
</div>
{%endblock%}

leave_app/templates/leave_app/form_create_2.html
{%extends 'root.html'%}

{%block content%}
<div>
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Отправить</button>
    </form>
</div>
{%endblock%}

leave_app/templates/leave_app/otgul_list.html
{%extends 'root.html'%}

{%block content%}
<form action="" method="get">
    {{filter_form.as_p}}
    <button type="submit">Найти</button>
</form>


    {%for otgul in otgul_list%}
    <a href="/leave-app/otkaz/{{otgul.id}}/?is_otpusk=false"><h3>{{otgul}}</h3></a>

    <p>ФИО: {{otgul.name}}</p>
    <p>Дата отгула: {{otgul.date}}</p>
    <p>Примечание: {{otgul.note}}</p>
    <p>Просмотрено: {% if otgul.prosmotreno%} ДА {%else%} НЕТ {%endif%}</p>

    {%if otgul.otkaz%}   
        <p>Причина отказа: {{otgul.otkaz.note}} </p>
        <p>Подпись: {{otgul.otkaz.name}} </p>
    {%elif otgul.prosmotreno%}
        <p>Одобрено</p>
    {%endif%}
    
    <p>Создано: {{otgul.created_date}}</p>
    <p>Отредактировано: {{otgul.edit_date}}</p>
    {%endfor%}
{%endblock%}

leave_app/templates/leave_app/otkaz.html
{%extends 'root.html'%}

{%block content%}
<div>
    <h3>Одобрить или отказать человку (отпуск/отгул)</h3>
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Сохранить</button>
    </form>
</div>
{%endblock%}

leave_app/templates/leave_app/otpusk_list.html
{% extends 'root.html'%}

{%block content%}

    <form action="" method="get">
        {{filter_form.as_p}}
        <button type="submit">Найти</button>
    </form>


    {%for otpusk in otpusk_list%}
    <a href="/leave-app/otkaz/{{otpusk.id}}/?is_otpusk=true"><h3>{{otpusk}}</h3></a>

    <p>ФИО: {{otpusk.name}}</p>
    <p>Начало отпуска: {{otpusk.start_date}}</p>
    <p>Конец отпуска: {{otpusk.end_date}}</p>
    <p>Примечание: {{otpusk.note}}</p>
    <p>Просмотрено: {% if otpusk.prosmotreno%} ДА {%else%} НЕТ {%endif%}</p>

    {%if otpusk.otkaz%}   
        <p>Причина отказа: {{otpusk.otkaz.note}} </p>
        <p>Подпись: {{otpusk.otkaz.name}} </p>
    {%elif otpusk.prosmotreno%}
        <p>Одобрено</p>
    {%endif%}
    <p>Создано: {{otpusk.created_date}}</p>
    <p>Отредактировано: {{otpusk.edit_date}}</p>
    {%endfor%}
{%endblock%}

templates/root.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div>
        <a class="nav" href="{% url 'leave_app:otpusk_list' %}"> Заявки отпуск</a>
        <a class="nav" href="{% url 'leave_app:otgul_list' %}"> Заявки отгул</a>
        <a class="nav" href="{% url 'leave_app:form_create' %}"> Создать заявку(отпуск)</a>
        <a class="nav" href="{% url 'leave_app:form_create_2' %}"> Создать заявку(отгул)</a>


   </div>

    {% block content%}
    {%endblock%}
</body>
</html>